### PR TITLE
v1.2.1 invalid confirmation

### LINKED ISSUE #35: User confirmation prompt
As a user, I would like to have confirmation when I perform commands like deleting a student so that I have a better peace of mind when it comes to the more dangerous commands

- Delete student particulars
- Clear student list
- Exit app

### LINKED ISSUE #78: User confirmation prompt: No explicit handling of erroneous input
Current: "Confirmation input is invalid!"
Expected should be somewhere along: "Confirmation input is invalid! Please input yes/no only!"

### PR DESCRIPTION
**Pull request by marcustw**

### CODE REVIEW

**Review by YuunoKun — APPROVED** [review]
LGTM

**Review by nweiyue — APPROVED** [review]
LGTM

**Comment by CodingCookieRookie** [comment]
LGTM

**Comment by marcustw** [comment]
Minor error in checkstyle after resolving merge conflict, resolved in PR #90

**Pull request merged**
